In [1]:
import numpy as np

Creating the Array

In [3]:
ar1 = np.array([1,2,3,4,5])
print(ar1)

[1 2 3 4 5]


Finding the shape of the array using .shape attribute

In [4]:
print(ar1.shape)

(5,)


Reshaping the array

In [7]:
ar1 = np.array([0,1,2,3,4,5])
reshaped_ar1 = ar1.reshape(2, 3)
print(reshaped_ar1)

[[0 1 2]
 [3 4 5]]


Finding the shape of new array

In [8]:
print(reshaped_ar1.shape)

(2, 3)


Creating another array

In [10]:
ar1=np.array([1,2,3,4,5])
ar2=np.array([6,7,8,9,10])
print(ar2)

[ 6  7  8  9 10]


Concatenating Two arrays

In [11]:
concatenated_ar = np.concatenate((ar1,ar2), axis=0)
print(concatenated_ar)

[ 1  2  3  4  5  6  7  8  9 10]


Computing the resultant array's mean,median and Standard deviation

In [12]:
mean_value = np.mean(concatenated_ar)
median_value = np.median(concatenated_ar)
std_value = np.std(concatenated_ar)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_value)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
